### PR TITLE
Modsecurity integration & configuration

### PR DESCRIPTION
**Pull request by bonfilsd**
_Proposed change:_

Adds support for Web Application Firewall following discussion in https://github.com/cloudfoundry/php-buildpack/issues/221#issuecomment-331185109 Sorry @sclevine for late follow up on this issue.

_Use cases your change solves:_

Provides WAF features in php buildpack natively. Orange used to maintain a php buildpack fork to get this feature.

* [x] I have made this pull request to the `develop` branch
* [ ] I have added an integration test. Guidance would be highly appreciated.

Note that once merged, a PR would then be submitted to https://github.com/cloudfoundry/docs-buildpacks/blob/master/php/index.html.md.erb to document the feature. For now, this documentation lives in the PR text.

--------------------------

### php-buildpack repository

_Detailed decription:_
- only apache httpd is supported 
- modsecurity core version is 2.9.2
- modsecurity Core Rule Set (CRS) version is 3.0.2

Also, by default, modsecurity module is not enabled.

```apache
#LoadModule security2_module modules/mod_security2.so
```

When enabling `mod_security` module, users also need to activate the `unique_id` module required as a dependency.

```apache
#LoadModule unique_id_module modules/mod_unique_id.so
```

In addition, for configuration file needs, 5 environments variables & directories have been created

* environment variables:
  * MODSECURITY_AUDIT_DIR
  * MODSECURITY_CRS_DIR
  * MODSECURITY_LOG_DIR
  * MODSECURITY_TMP_DIR
  * MODSECURITY_UPLOAD_DIR

* directories:
  * app/modsecurity/audit
  * app/modsecurity/crs # for rules and configuration files
  * app/modsecurity/log
  * app/modsecurity/tmp
  * app/modsecurity/upload

### binary-builder repository
Obviously, new recipe for httpd is needed to the manifest.yml file.

This recipe is available in the following modsecurity branch (pending related PR)
* https://github.com/orange-cloudfoundry/binary-builder/tree/modsecurity

and comparison here : 
* https://github.com/orange-cloudfoundry/binary-builder/compare/master...orange-cloudfoundry:modsecurity

### docs-buildpacks repository
In addition, documentation has been done to explain how to activate & configure modsecurity for PHP buildpack.

This documentation is available in the following modsecurity branch (pending related PR)
* https://github.com/bonfilsd/docs-buildpacks/tree/modsecurity

and PR here
* https://github.com/orange-cloudfoundry/docs-buildpacks/pull/1

and comparison here :
* https://github.com/orange-cloudfoundry/docs-buildpacks/compare/modsecurity...bonfilsd:modsecurity

Thanks in advance for your feedback 

--

### CODE REVIEW

**Comment by gberche-orange** [comment]
thanks @bonfilsd I've quickly edited the PR text. I'll leave it up to @ArthurHlt for code review.

**Comment by ArthurHlt** [comment]
As a side note, modsecurity support nginx too. They would probably ask to do the work for nginx.

@gberche-orange What's your thoughts about that ? I would rather wait them to ask about it and don't think about it for now

**Comment by bonfilsd** [comment]
@ArthurHlt in response on your review

* Add modsecurity dependencies in manifest.yml

There is no dependencies needs for modsecurity.
It's included and compiled in http recipe of binary-builder

* Clean at least, non-relative php conf files

After discussion, the policy seems more simple to keep default CRS rules rather than customize it.
This choice seems to be more efficient for future evolutions and mostly less restrictive.

**Comment by gberche-orange** [comment]
> As a side note, modsecurity support nginx too. They would probably ask to do the work for nginx.
> What's your thoughts about that ? I would rather wait them to ask about it and don't think about it for now

@ArthurHlt 

The PR description makes it clear `only apache httpd is supported`. I would suggest to submit the PR with the apache support first and not risk to wait for nginx support that could delay the contribution.

**Comment by gberche-orange** [comment]
@ArthurHlt can you update your review to unlock @bonfilsd so that he submits his pr upstream ?

**Comment by gberche-orange** [comment]
@bonfilsd please goahead, and feel free to submit the PR upstream

**Pull request merged**
